// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import BikersController from "./bikers_controller"
application.register("bikers", BikersController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InfoCardController from "./info_card_controller"
application.register("info-card", InfoCardController)

import MapController from "./map_controller"
application.register("map", MapController)

import MapMeetingPointController from "./map_meeting_point_controller"
application.register("map-meeting-point", MapMeetingPointController)

import QuestionFormController from "./question_form_controller"
application.register("question-form", QuestionFormController)

import SearchQuestionsController from "./search_questions_controller"
application.register("search-questions", SearchQuestionsController)

import ToggleFiltersMenuController from "./toggle_filters_menu_controller"
application.register("toggle-filters-menu", ToggleFiltersMenuController)

import UserMapCardController from "./user_map_card_controller"
application.register("user-map-card", UserMapCardController)
